### ISSUE TITLE
Get with file does not callback

### ISSUE THREAD

**Issue by msimr** [SaltwaterC/http-request#1]
I get into a file and the callback is never triggered.

http.get({url:url}, encryptedURL, function (err, res) {console.log(err,res);});

This never prints in my case.

However the file is downloaded without errors.

**Comment by SaltwaterC** [comment]
Scratch the previous part. It appears to be an issue. I'll have a proper look.

**Comment by SaltwaterC** [comment]
Happens only with multiple data events when the gzbz2 module is missing.

**Comment by SaltwaterC** [comment]
There was a pretty subtle race condition there. In single data event cases, the end of transfer event was fired before the write stream file descriptor was available. I made a workaround that broke the other case: having the fd available before the end of transfer event kicks in. I'll update the test coverage to properly assert these conditions, both with gzip enabled and disabled.

**Comment by msimr** [comment]
I'm testing it on my side will keep you posted with the results.

**Comment by msimr** [comment]
Works fine.

Thanks for the fix!

**Comment by SaltwaterC** [comment]
You're welcome.
