### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by niczak** [SaltwaterC/http-request#23]
Does this module work in Windows?  I get the following error when running 'npm install http-request'

gyp http GET http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Testing\v1\node_modules\http-request\node_modules\mmmagic
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok
npm ERR! mmmagic@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.5 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "http-request"
npm ERR! cwd C:\Testing\v1
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Testing\v1\npm-debug.log
npm ERR! not ok code 0

**Comment by SaltwaterC** [comment]
Hi. There seems to be an issue with the mmmagic dependency that this module uses. Except mmmagic, is all JS that should work under Windows without issues.

The mmmagic module is only used for the MIME sniffer and for PUT requests that don't have a specified Content-Type. Worse case scenario: I'll make it an optional dependency and patch it to work without it with degraded functionality.

Summoning @mscdex who is in charge for mmmagic.

**Comment by niczak** [comment]
@SaltwaterC @mscdex Thank you very much for looking into this!

**Comment by mscdex** [comment]
This is unrelated to mmmagic as it hasn't even gotten to building mmmagic yet. It looks like you're having some issue with the node source tarball. Are you behind a firewall or proxy of some kind?

**Comment by niczak** [comment]
@mscdex I am behind a corporate firewall but haven't had any issues installing other modules.  Is there a unique port I should be aware of or a specific server I should check?

**Comment by mscdex** [comment]
The only time you should have had trouble installing modules on that machine is when they were bindings, requiring compilation. Are you able to go to [http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz](http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz) in a browser on that machine? If so, is there an http/socks proxy set in that browser's network settings?

**Comment by niczak** [comment]
@mscdex Holy crap, you are right.  That site is blocked by our firewall which makes absolutely zero sense.  I will get that rule lifted and try again.  Thank you for your input!

**Comment by niczak** [comment]
White listed and boom, npm worked.  Thank you so much for your assistance!  I am closing this out now.  Cheers @mscdex / @SaltwaterC.
