### ISSUE TITLE
please update npm

### ISSUE THREAD

**Issue by jasonkarns** [SaltwaterC/http-request#25]
If http-request is the successor to http-get, please clean up npm. It's really confusing having two different npm packages pointing to the same git repo.

If http-get is retired, please deprecate the package on npm.

**Comment by SaltwaterC** [comment]
Thanks for the heads up. I was unaware that I could deprecate packages on npm. http-get is retired for good. Is this OK?

``` bash
npm install http-get
npm http GET https://registry.npmjs.org/http-get
npm http 200 https://registry.npmjs.org/http-get
npm WARN deprecated http-get@0.5.10: http-get has reached its end of life. Please use its successor: http-request.
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/buffer-concat
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/buffer-concat
http-get@0.5.10 node_modules/http-get
├── buffer-concat@0.0.1
└── semver@2.2.1
```

I wanted to make something like a transitional package (kinda like Debian and friends do), but then I forgot about it.

**Comment by jasonkarns** [comment]
thanks!

**Comment by SaltwaterC** [comment]
You're welcome.
