### ISSUE TITLE
Dependency install not working in v0.6.4

### ISSUE THREAD

**Issue by msimr** [SaltwaterC/http-request#3]
There is a problem with gzbz2 at the moment.
Any alternatives?

**Comment by SaltwaterC** [comment]
You may try to use it without gzbz2 (if that is not an issue) till the gzip support gets ported to the native zlib support in node 0.6.x.

**Comment by SaltwaterC** [comment]
v0.4 doesn't depend on gzbz2 anymore. It uses the native zlib support.
