### ISSUE TITLE
Python required to install

### ISSUE THREAD

**Issue by SHaTRO** [SaltwaterC/http-request#30]
your dependency on "mmagic" requires Python, so it does not install on Windows.  Really shouldn't need Python for node modules anyhow.

<pre>
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Projects\workspace\uie\metrics\node_modules\http-request\node_modules\mmmagic
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-request" "--save"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.15 install script 'node-gyp rebuild'.
</pre>

**Comment by SaltwaterC** [comment]
Unfortunately, I'm not familiar with node.js under Windows, or how mmmagic should build under Windows.

CC @mscdex

**Comment by mscdex** [comment]
Python and MSVC (Express versions work fine) are required to compile any node addon on Windows, just like you need Python and GCC/G++ on *nix to build node addons. Install those missing components and you should be good to go. See the [`node-gyp` readme](https://github.com/TooTallNate/node-gyp) for more detailed information about more specific requirements.
