### ISSUE TITLE
auth is broken

### ISSUE THREAD

**Issue by elarcent** [SaltwaterC/http-request#9]
I've found that URLs that require authorization(http://user:pass@url.com) are not requested properly.
I had to disable 

``` javascript
        if (url.auth) {
            console.log('Brokern Auth!');
            opt.headers.authorization = new Buffer(url.auth).toString('base64');
        }
```

in tools.js, and to add simple      

``` javascript
opt.auth = url.auth;
```

few strings above, to make it work properly

**Comment by SaltwaterC** [comment]
Thank you for taking the time to explain the issue. The fix was merged in the future v0.4.1.
